# Generated by Django 5.2.5 on 2025-09-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id_vehicule', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicules/')),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('kilometrageinitiale', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Louer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_finlocation', models.DateField()),
                ('kilometrageapreslocation', models.IntegerField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.client')),
                ('id_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.vehicule')),
            ],
        ),
    ]
