# Generated by Django 5.2.5 on 2025-09-03 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_client_user_alter_client_adresse_alter_client_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='louer',
            name='id_client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.client'),
        ),
        migrations.AlterField(
            model_name='louer',
            name='id_vehicule',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='location.vehicule'),
        ),
    ]
