# Generated by Django 5.2.5 on 2025-09-05 10:50

import location.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_louer_id_client_alter_louer_id_vehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='louer',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='louer',
            name='kilometrageapreslocation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=location.models.vehicule_upload_path),
        ),
    ]
