# Generated by Django 5.2.5 on 2025-09-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_louer_statut_alter_louer_kilometrageapreslocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='louer',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
