# Generated by Django 5.2.5 on 2025-09-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_client_created_at_louer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tel',
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
