# Generated by Django 5.2.5 on 2025-09-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_remove_client_tel_client_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
