# Generated by Django 5.2.5 on 2025-09-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_client_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='confirmation_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
